/**
 * Reusable skill parser that splits pasted text into individual skill chips.
 * Supports commas, semicolons, vertical bars, newlines, tabs, and bullet points.
 */

const SEPARATOR_REGEX = /[,;|\\\n\t\u2022\u25CF\u25CB\u25AA\u25B8]+/;

export function parseSkillsInput(raw: string): string[] {
  if (!raw || !raw.trim()) return [];
  const parts = raw.split(SEPARATOR_REGEX);
  const skills: string[] = [];
  const seen = new Set<string>();
  for (let part of parts) {
    let skill = part.trim();
    skill = skill.replace(/^[•·\-\s]+|[\s]+$/g, '').trim();
    skill = skill.replace(/^[\(\)\[\]{}]+|[\(\)\[\]{}]+$/g, '').trim();
    if (!skill) continue;
    const lower = skill.toLowerCase();
    if (seen.has(lower)) continue;
    seen.add(lower);
    skills.push(skill);
  }
  return skills;
}

export function parseSkillsInputMerge(
  raw: string,
  existing: string[]
): string[] {
  const newSkills = parseSkillsInput(raw);
  const seen = new Set(existing.map((s) => s.toLowerCase()));
  const result = [...existing];
  for (const s of newSkills) {
    if (!seen.has(s.toLowerCase())) {
      result.push(s);
      seen.add(s.toLowerCase());
    }
  }
  return result;
}

/**
 * Skill normalization and alias matching.
 * Maps common variations to a canonical normalized form for matching.
 */
const ALIAS_MAP: Record<string, string> = {
  js: 'javascript', javascript: 'javascript', es6: 'javascript', es2015: 'javascript',
  ts: 'typescript', typescript: 'typescript',
  react: 'react', 'react.js': 'react', reactjs: 'react', 'react js': 'react',
  'next.js': 'next.js', nextjs: 'next.js', 'next js': 'next.js', next: 'next.js',
  node: 'node.js', 'node.js': 'node.js', nodejs: 'node.js', 'node js': 'node.js',
  vue: 'vue', 'vue.js': 'vue', vuejs: 'vue', 'vue js': 'vue',
  angular: 'angular', angularjs: 'angular', 'angular.js': 'angular', 'angular js': 'angular',
  postgres: 'postgresql', postgresql: 'postgresql', 'postgres sql': 'postgresql',
  mongo: 'mongodb', mongodb: 'mongodb', 'mongo db': 'mongodb',
  github: 'git', git: 'git',
  html5: 'html', html: 'html',
  css3: 'css', css: 'css',
  'fast api': 'fastapi', fastapi: 'fastapi', 'fast-api': 'fastapi',
  express: 'express', 'express.js': 'express', expressjs: 'express', 'express js': 'express',
  'spring boot': 'spring boot', springboot: 'spring boot', 'spring-boot': 'spring boot', spring: 'spring',
  rails: 'rails', 'ruby on rails': 'rails',
  cpp: 'c++', 'c plus plus': 'c++', 'c++': 'c++',
  csharp: 'c#', 'c sharp': 'c#', 'c#': 'c#',
  golang: 'go', go: 'go',
  rust: 'rust', python: 'python', python3: 'python', 'python 3': 'python',
  java: 'java', kotlin: 'kotlin', swift: 'swift', php: 'php', laravel: 'laravel', ruby: 'ruby',
  docker: 'docker', kubernetes: 'kubernetes', k8s: 'kubernetes',
  aws: 'aws', 'amazon web services': 'aws', 'amazon aws': 'aws',
  azure: 'azure', 'microsoft azure': 'azure',
  gcp: 'gcp', 'google cloud': 'gcp', 'google cloud platform': 'gcp',
  redis: 'redis', graphql: 'graphql', rest: 'rest', restful: 'rest',
  'rest api': 'rest api', 'rest apis': 'rest api', 'restful api': 'rest api',
  elasticsearch: 'elasticsearch', 'elastic search': 'elasticsearch',
  kafka: 'kafka', 'apache kafka': 'kafka',
  rabbitmq: 'rabbitmq', 'rabbit mq': 'rabbitmq',
  jenkins: 'jenkins', 'ci/cd': 'ci/cd', cicd: 'ci/cd', 'ci cd': 'ci/cd',
  terraform: 'terraform', ansible: 'ansible', linux: 'linux',
  bash: 'bash', shell: 'bash', 'shell scripting': 'bash', powershell: 'powershell',
  'machine learning': 'machine learning', ml: 'machine learning',
  'deep learning': 'deep learning', dl: 'deep learning',
  tensorflow: 'tensorflow', 'tensor flow': 'tensorflow',
  pytorch: 'pytorch', 'py torch': 'pytorch',
  pandas: 'pandas', numpy: 'numpy',
  'scikit-learn': 'scikit-learn', scikit: 'scikit-learn', sklearn: 'scikit-learn', 'scikit learn': 'scikit-learn',
  spark: 'spark', 'apache spark': 'spark', hadoop: 'hadoop', 'apache hadoop': 'hadoop',
  airflow: 'airflow', 'apache airflow': 'airflow',
  tableau: 'tableau', 'power bi': 'power bi', powerbi: 'power bi',
  excel: 'excel', sql: 'sql', nosql: 'nosql', 'no sql': 'nosql',
  microservices: 'microservices', 'micro services': 'microservices', 'micro-services': 'microservices',
  agile: 'agile', scrum: 'scrum', jira: 'jira',
  testing: 'testing', 'unit testing': 'testing', jest: 'jest', cypress: 'cypress', selenium: 'selenium',
  pytest: 'pytest', 'py test': 'pytest',
  'object-oriented programming': 'oop', oop: 'oop', 'object oriented programming': 'oop',
  'natural language processing': 'nlp', nlp: 'nlp',
  'data structures': 'data structures', 'data structure': 'data structures',
  algorithms: 'algorithms', 'computer networks': 'computer networks',
  'computer network': 'computer networks',
  'operating systems': 'operating systems', 'operating system': 'operating systems',
  'data science': 'data science', 'data analytics': 'data analytics',
  'data analysis': 'data analysis', 'data visualization': 'data visualization',
  'big data': 'big data', devops: 'devops', 'dev ops': 'devops', 'dev-ops': 'devops',
  sre: 'sre', 'site reliability': 'sre', 'site reliability engineering': 'sre',
  'user experience': 'ux', ux: 'ux', 'user interface': 'ui', ui: 'ui',
  figma: 'figma', tailwind: 'tailwind', tailwindcss: 'tailwind', 'tailwind css': 'tailwind',
  sass: 'sass', scss: 'sass', 'styled components': 'styled-components', 'styled-components': 'styled-components',
  redux: 'redux', webpack: 'webpack', vite: 'vite', babel: 'babel',
  eslint: 'eslint', prettier: 'prettier',
  vscode: 'vscode', 'vs code': 'vscode', 'visual studio code': 'vscode',
  postman: 'postman', swagger: 'swagger', openapi: 'openapi', 'open api': 'openapi',
  grpc: 'grpc', websocket: 'websocket', websockets: 'websocket', 'web sockets': 'websocket',
  'socket.io': 'socket.io', socketio: 'socket.io', 'socket io': 'socket.io',
  'react native': 'react native', reactnative: 'react native',
  flutter: 'flutter', dart: 'dart', electron: 'electron',
  unity: 'unity', 'unreal engine': 'unreal engine', unreal: 'unreal engine',
  opencv: 'opencv', 'open cv': 'opencv', matplotlib: 'matplotlib', seaborn: 'seaborn',
  scipy: 'scipy', xgboost: 'xgboost', lightgbm: 'lightgbm',
  huggingface: 'huggingface', 'hugging face': 'huggingface',
  transformers: 'transformers', langchain: 'langchain', 'lang chain': 'langchain',
  openai: 'openai', 'open ai': 'openai', anthropic: 'anthropic',
  mysql: 'mysql', mariadb: 'mariadb', 'maria db': 'mariadb',
  percona: 'percona', couchbase: 'couchbase', couchdb: 'couchdb', 'couch db': 'couchdb',
  neo4j: 'neo4j', 'neo 4j': 'neo4j',
  dynamodb: 'dynamodb', 'amazon dynamodb': 'dynamodb',
  s3: 's3', 'amazon s3': 's3', ec2: 'ec2', 'amazon ec2': 'ec2',
  lambda: 'lambda', 'aws lambda': 'lambda', 'amazon lambda': 'lambda',
  'api gateway': 'api gateway', 'amazon api gateway': 'api gateway',
  django: 'django', flask: 'flask',
  celery: 'celery', nginx: 'nginx', prometheus: 'prometheus', grafana: 'grafana',
  elm: 'elm', erlang: 'erlang', elixir: 'elixir', phoenix: 'phoenix',
  scala: 'scala', groovy: 'groovy', perl: 'perl', lua: 'lua',
  r: 'r', julia: 'julia', matlab: 'matlab',
  'asp.net': 'asp.net', 'asp net': 'asp.net', aspnet: 'asp.net',
  'asp.net core': 'asp.net core', 'asp net core': 'asp.net core', aspnetcore: 'asp.net core',
  '.net': '.net', dotnet: '.net', 'dot net': '.net',
  'entity framework': 'entity framework', 'entity framework core': 'entity framework',
  'ef core': 'entity framework', ef: 'entity framework',
  linq: 'linq', 'language integrated query': 'linq',
  c: 'c', 'c language': 'c',
  'objective-c': 'objective-c', 'objective c': 'objective-c', objc: 'objective-c',
  'f#': 'f#', fsharp: 'f#', 'f sharp': 'f#',
  clojure: 'clojure', clojurescript: 'clojurescript', 'clojure script': 'clojurescript',
  haskell: 'haskell', ocaml: 'ocaml',
  svelte: 'svelte', sveltekit: 'svelte', 'svelte kit': 'svelte',
  solid: 'solid', solidjs: 'solid', 'solid js': 'solid',
  astro: 'astro', remix: 'remix', gatsby: 'gatsby', nuxt: 'nuxt',
  quasar: 'quasar', vuetify: 'vuetify', 'element ui': 'element ui', elementui: 'element ui',
  'ant design': 'ant design', antdesign: 'ant design', antd: 'ant design',
  'material ui': 'material ui', 'material-ui': 'material ui', mui: 'material ui',
  'chakra ui': 'chakra ui', chakraui: 'chakra ui', chakra: 'chakra ui',
  mantine: 'mantine', 'headless ui': 'headless ui', headlessui: 'headless ui',
  'radix ui': 'radix ui', radix: 'radix ui', 'radix-ui': 'radix ui',
  shadcn: 'shadcn', 'shadcn ui': 'shadcn', 'shadcn/ui': 'shadcn', shadcnui: 'shadcn',
  recharts: 'recharts', 'chart.js': 'chart.js', chartjs: 'chart.js', 'chart js': 'chart.js',
  d3: 'd3', 'd3.js': 'd3', d3js: 'd3', 'd3 js': 'd3',
  'three.js': 'three.js', threejs: 'three.js', 'three js': 'three.js', three: 'three.js',
  'framer motion': 'framer motion', framer: 'framer motion',
  'react spring': 'react spring', 'react-spring': 'react spring',
  'react hook form': 'react hook form', reacthookform: 'react hook form', 'react-hook-form': 'react hook form',
  'react query': 'react query', reactquery: 'react query', 'react-query': 'react query',
  'tanstack query': 'react query', 'tanstack table': 'tanstack table',
  'react table': 'tanstack table', 'react-table': 'tanstack table',
  zustand: 'zustand', jotai: 'jotai', recoil: 'recoil', valtio: 'valtio',
  xstate: 'xstate', 'x-state': 'xstate',
  'react dnd': 'react dnd', 'react-dnd': 'react dnd', reactdnd: 'react dnd',
  pnpm: 'pnpm', yarn: 'yarn', npm: 'npm',
  bun: 'bun', deno: 'deno',
  parcel: 'parcel', esbuild: 'esbuild', swc: 'swc',
  flyway: 'flyway', liquibase: 'liquibase', alembic: 'alembic',
  prisma: 'prisma', typeorm: 'typeorm', sequelize: 'sequelize', mongoose: 'mongoose',
  knex: 'knex', sqlalchemy: 'sqlalchemy',
  sentry: 'sentry', datadog: 'datadog', 'new relic': 'new relic', newrelic: 'new relic',
  splunk: 'splunk', kibana: 'kibana', logstash: 'logstash',
  'elk': 'elk stack', 'elk stack': 'elk stack',
  helm: 'helm', 'helm charts': 'helm',
  'argo cd': 'argo cd', argocd: 'argo cd',
  tekton: 'tekton', spinnaker: 'spinnaker',
  circleci: 'circleci', 'circle ci': 'circleci',
  'travis ci': 'travis ci', travis: 'travis ci',
  'github actions': 'github actions', 'gitlab ci': 'gitlab ci',
  sonarqube: 'sonarqube', 'sonar qube': 'sonarqube', sonar: 'sonarqube',
  jacoco: 'jacoco', istanbul: 'istanbul',
  'code coverage': 'code coverage',
  looker: 'looker', 'looker studio': 'looker studio', 'google data studio': 'looker studio',
  'qlik sense': 'qlik sense', qlikview: 'qlik sense', qlik: 'qlik sense',
  domo: 'domo', sisense: 'sisense',
  mlflow: 'mlflow', kubeflow: 'kubeflow', sagemaker: 'sagemaker', 'aws sagemaker': 'sagemaker',
  'vertex ai': 'vertex ai', 'azure ml': 'azure ml', 'azure machine learning': 'azure ml',
  wandb: 'wandb', 'weights and biases': 'wandb',
  dvc: 'dvc', 'data version control': 'dvc',
  dbt: 'dbt', 'data build tool': 'dbt',
  prefect: 'prefect', dagster: 'dagster',
  airbyte: 'airbyte', fivetran: 'fivetran',
  segment: 'segment', amplitude: 'amplitude', mixpanel: 'mixpanel',
  'google analytics': 'google analytics', ga4: 'google analytics',
  hotjar: 'hotjar', logrocket: 'logrocket', posthog: 'posthog',
  launchdarkly: 'launchdarkly', optimizely: 'optimizely',
  firebase: 'firebase', firestore: 'firestore', 'google firestore': 'firestore',
  auth0: 'auth0', okta: 'okta', keycloak: 'keycloak',
  stripe: 'stripe', twilio: 'twilio', sendgrid: 'sendgrid',
  slack: 'slack', 'slack api': 'slack',
  apollo: 'apollo graphql', 'apollo graphql': 'apollo graphql', 'graphql apollo': 'apollo graphql',
  netty: 'netty', vertx: 'vertx', 'vert.x': 'vertx',
  rxjava: 'rxjava', 'rx java': 'rxjava',
  reactor: 'reactor', 'project reactor': 'reactor',
  akka: 'akka', 'akka streams': 'akka streams',
  disruptor: 'disruptor',
  pillow: 'pillow', pil: 'pillow',
  plotly: 'plotly', bokeh: 'bokeh',
  statsmodels: 'statsmodels', catboost: 'catboost',
  llamaindex: 'llamaindex', 'llama index': 'llamaindex',
  pinecone: 'pinecone', 'pine cone': 'pinecone',
  weaviate: 'weaviate', qdrant: 'qdrant', milvus: 'milvus',
  chroma: 'chroma', chromadb: 'chroma',
  cohere: 'cohere', replicate: 'replicate',
  diffusers: 'diffusers', accelerate: 'accelerate', peft: 'peft',
  cassandra: 'cassandra', 'apache cassandra': 'cassandra',
  solr: 'solr', 'apache solr': 'solr',
  documentdb: 'documentdb', 'amazon documentdb': 'documentdb', 'document db': 'documentdb',
  msk: 'msk', 'managed streaming for kafka': 'msk',
  confluent: 'confluent', 'confluent kafka': 'confluent',
  'kafka connect': 'kafka connect', 'kafka streams': 'kafka streams',
  ksqldb: 'ksqldb', 'kafka ksql': 'ksqldb',
  pulsar: 'pulsar', 'apache pulsar': 'pulsar',
  avro: 'avro', 'apache avro': 'avro',
  parquet: 'parquet', 'apache parquet': 'parquet',
  orc: 'orc', 'apache orc': 'orc',
  arrow: 'arrow', 'apache arrow': 'arrow',
  beam: 'beam', 'apache beam': 'beam',
  'apache flink': 'apache flink', flink: 'apache flink',
  impala: 'impala', 'apache impala': 'impala',
  kudu: 'kudu', 'apache kudu': 'kudu',
  'apache phoenix': 'apache phoenix',
  'apache hive': 'apache hive', hive: 'apache hive',
  'apache hbase': 'apache hbase', hbase: 'apache hbase',
  sqoop: 'sqoop', 'apache sqoop': 'sqoop',
  oozie: 'oozie', 'apache oozie': 'oozie',
  flume: 'flume', 'apache flume': 'flume',
  zeppelin: 'zeppelin', 'apache zeppelin': 'zeppelin',
  kylin: 'kylin', 'apache kylin': 'kylin',
  'apache drill': 'apache drill', drill: 'apache drill',
  tajo: 'tajo', 'apache tajo': 'tajo',
  livy: 'livy', 'apache livy': 'livy',
  eagle: 'eagle', 'apache eagle': 'eagle',
  slider: 'slider', 'apache slider': 'slider',
  twill: 'twill', 'apache twill': 'twill',
  yetus: 'yetus', 'apache yetus': 'yetus',
  ranger: 'ranger', 'apache ranger': 'ranger',
  atlas: 'atlas', 'apache atlas': 'atlas',
  knox: 'knox', 'apache knox': 'knox',
  metron: 'metron', 'apache metron': 'metron',
  jspwiki: 'jspwiki', 'apache jspwiki': 'jspwiki',
  roller: 'roller', 'apache roller': 'roller',
  streams: 'streams', 'apache streams': 'streams',
  mnemonics: 'mnemonics', 'apache mnemonics': 'mnemonics',
  opennlp: 'opennlp', 'apache opennlp': 'opennlp', 'open nlp': 'opennlp',
  uima: 'uima', 'apache uima': 'uima',
  cxf: 'cxf', 'apache cxf': 'cxf',
  axis: 'axis', 'apache axis': 'axis', axis2: 'axis', 'apache axis2': 'axis',
  wss4j: 'wss4j', 'apache wss4j': 'wss4j',
  santuario: 'santuario', 'apache santuario': 'santuario',
  'xml security': 'xml security', 'apache xml security': 'xml security',
  xalan: 'xalan', 'apache xalan': 'xalan',
  xerces: 'xerces', 'apache xerces': 'xerces',
  xmlbeans: 'xmlbeans', 'apache xmlbeans': 'xmlbeans',
  commons: 'commons', 'apache commons': 'commons',
  httpclient: 'httpclient', 'apache httpclient': 'httpclient', 'http client': 'httpclient',
  httpcomponents: 'httpcomponents', 'apache httpcomponents': 'httpcomponents', 'http components': 'httpcomponents',
  mime4j: 'mime4j', 'apache mime4j': 'mime4j',
  james: 'james', 'apache james': 'james',
  jsp: 'jsp', 'apache jsp': 'jsp',
  myfaces: 'myfaces', 'apache myfaces': 'myfaces',
  tomee: 'tomee', 'apache tomee': 'tomee',
  geronimo: 'geronimo', 'apache geronimo': 'geronimo',
  openejb: 'openejb', 'apache openejb': 'openejb',
  openwebbeans: 'openwebbeans', 'apache openwebbeans': 'openwebbeans',
  deltaspike: 'deltaspike', 'apache deltaspike': 'deltaspike',
  tapestry: 'tapestry', 'apache tapestry': 'tapestry',
  wicket: 'wicket', 'apache wicket': 'wicket',
  struts: 'struts', 'apache struts': 'struts',
  shale: 'shale', 'apache shale': 'shale',
  beehive: 'beehive', 'apache beehive': 'beehive', 'apache bee hive': 'beehive',
  xmlgraphics: 'xmlgraphics', 'apache xmlgraphics': 'xmlgraphics',
  batik: 'batik', 'apache batik': 'batik',
  fop: 'fop', 'apache fop': 'fop',
  pdfbox: 'pdfbox', 'apache pdfbox': 'pdfbox',
  poi: 'poi', 'apache poi': 'poi',
  odfdom: 'odfdom', 'apache odfdom': 'odfdom',
  'commons compress': 'commons compress', 'apache commons compress': 'commons compress',
  'commons csv': 'commons csv', 'apache commons csv': 'commons csv',
  'commons io': 'commons io', 'apache commons io': 'commons io',
  'commons lang': 'commons lang', 'apache commons lang': 'commons lang',
  'commons math': 'commons math', 'apache commons math': 'commons math',
  'commons net': 'commons net', 'apache commons net': 'commons net',
  'commons pool': 'commons pool', 'apache commons pool': 'commons pool',
  'commons dbcp': 'commons dbcp', 'apache commons dbcp': 'commons dbcp',
  'commons dbutils': 'commons dbutils', 'apache commons dbutils': 'commons dbutils',
  'commons fileupload': 'commons fileupload', 'apache commons fileupload': 'commons fileupload',
  'commons validator': 'commons validator', 'apache commons validator': 'commons validator',
  'commons cli': 'commons cli', 'apache commons cli': 'commons cli',
  'commons codec': 'commons codec', 'apache commons codec': 'commons codec',
  'commons collections': 'commons collections', 'apache commons collections': 'commons collections',
  'commons configuration': 'commons configuration', 'apache commons configuration': 'commons configuration',
  'commons daemon': 'commons daemon', 'apache commons daemon': 'commons daemon',
  'commons digester': 'commons digester', 'apache commons digester': 'commons digester',
  'commons discovery': 'commons discovery', 'apache commons discovery': 'commons discovery',
  'commons el': 'commons el', 'apache commons el': 'commons el',
  'commons exec': 'commons exec', 'apache commons exec': 'commons exec',
  'commons jci': 'commons jci', 'apache commons jci': 'commons jci',
  'commons jcs': 'commons jcs', 'apache commons jcs': 'commons jcs',
  'commons jexl': 'commons jexl', 'apache commons jexl': 'commons jexl',
  'commons jxpath': 'commons jxpath', 'apache commons jxpath': 'commons jxpath',
  'commons launcher': 'commons launcher', 'apache commons launcher': 'commons launcher',
  'commons logging': 'commons logging', 'apache commons logging': 'commons logging',
  'commons modeler': 'commons modeler', 'apache commons modeler': 'commons modeler',
  'commons ognl': 'commons ognl', 'apache commons ognl': 'commons ognl',
  'commons prng': 'commons prng', 'apache commons prng': 'commons prng',
  'commons proxy': 'commons proxy', 'apache commons proxy': 'commons proxy',
  'commons scxml': 'commons scxml', 'apache commons scxml': 'commons scxml',
  'commons transaction': 'commons transaction', 'apache commons transaction': 'commons transaction',
  'commons vfs': 'commons vfs', 'apache commons vfs': 'commons vfs',
  droids: 'droids', 'apache droids': 'droids',
  imperius: 'imperius', 'apache imperius': 'imperius',
  log4j: 'log4j', 'apache log4j': 'log4j', 'log4j 2': 'log4j', log4j2: 'log4j',
  slf4j: 'slf4j', logback: 'logback', 'logback classic': 'logback',
  tinylog: 'tinylog', blitz4j: 'blitz4j',
  jboss: 'jboss', wildfly: 'wildfly',
  tomcat: 'tomcat', 'apache tomcat': 'tomcat',
  jetty: 'jetty', 'eclipse jetty': 'jetty',
  undertow: 'undertow',
  jgroups: 'jgroups',
  hazelcast: 'hazelcast', ignite: 'ignite', 'apache ignite': 'ignite',
  ehcache: 'ehcache', caffeine: 'caffeine', 'guava cache': 'guava cache',
  memcached: 'memcached', spymemcached: 'memcached', xmemcached: 'memcached',
  redisson: 'redisson', lettuce: 'lettuce', jedis: 'jedis',
  'spring data jpa': 'spring data jpa', 'spring data': 'spring data',
  'spring security': 'spring security', 'spring batch': 'spring batch',
  'spring cloud': 'spring cloud', 'spring webflux': 'spring webflux',
  'spring mvc': 'spring mvc', 'spring integration': 'spring integration',
  'spring amqp': 'spring amqp', 'spring kafka': 'spring kafka',
  'spring data mongodb': 'spring data mongodb', 'spring data mongo': 'spring data mongodb',
  'spring data neo4j': 'spring data neo4j', 'spring data rest': 'spring data rest',
  'spring hateoas': 'spring hateoas', 'spring session': 'spring session',
  'spring websocket': 'spring websocket', 'spring messaging': 'spring messaging',
  'spring retry': 'spring retry', 'spring statemachine': 'spring statemachine',
  'spring vault': 'spring vault',
  'spring cloud config': 'spring cloud config', 'spring cloud gateway': 'spring cloud gateway',
  'spring cloud netflix': 'spring cloud netflix', 'spring cloud stream': 'spring cloud stream',
  'spring cloud bus': 'spring cloud bus', 'spring cloud task': 'spring cloud task',
  'spring cloud data flow': 'spring cloud data flow', 'spring cloud skipper': 'spring cloud skipper',
  'spring cloud deployer': 'spring cloud deployer', 'spring cloud function': 'spring cloud function',
  'spring cloud openfeign': 'spring cloud openfeign', 'spring cloud sleuth': 'spring cloud sleuth',
  'spring cloud zipkin': 'spring cloud zipkin', 'spring cloud contract': 'spring cloud contract',
  'spring cloud security': 'spring cloud security', 'spring cloud consul': 'spring cloud consul',
  'spring cloud zookeeper': 'spring cloud zookeeper', 'spring cloud kubernetes': 'spring cloud kubernetes',
  'spring cloud aws': 'spring cloud aws', 'spring cloud gcp': 'spring cloud gcp',
  'spring cloud azure': 'spring cloud azure', 'spring cloud foundry': 'spring cloud foundry',
  'spring cloud cloudfoundry': 'spring cloud foundry',
  'spring rest docs': 'spring rest docs', 'spring restdocs': 'spring rest docs',
  springfox: 'springfox', 'springfox swagger': 'springfox',
  springdoc: 'springdoc', 'springdoc openapi': 'springdoc', 'springdoc-openapi': 'springdoc',
  'spring boot starter web': 'spring boot', 'spring boot starter data jpa': 'spring boot',
  'spring boot starter security': 'spring boot', 'spring boot starter test': 'spring boot',
  'spring boot starter actuator': 'spring boot', 'spring boot starter validation': 'spring boot',
  'spring boot starter data redis': 'spring boot', 'spring boot starter data mongodb': 'spring boot',
  'spring boot starter amqp': 'spring boot', 'spring boot starter kafka': 'spring boot',
  'spring boot starter websocket': 'spring boot', 'spring boot starter webflux': 'spring boot',
  'spring boot starter batch': 'spring boot', 'spring boot starter cloud': 'spring boot',
  'spring boot starter mail': 'spring boot', 'spring boot starter thymeleaf': 'spring boot',
  'spring boot starter freemarker': 'spring boot', 'spring boot starter mustache': 'spring boot',
  'spring boot starter groovy templates': 'spring boot', 'spring boot starter data rest': 'spring boot',
  'spring boot starter data neo4j': 'spring boot', 'spring boot starter data elasticsearch': 'spring boot',
  'spring boot starter data cassandra': 'spring boot', 'spring boot starter data ldap': 'spring boot',
  'spring boot starter data solr': 'spring boot', 'spring boot starter data influxdb': 'spring boot',
  'spring boot starter data couchbase': 'spring boot', 'spring boot starter cache': 'spring boot',
  'spring boot starter jta': 'spring boot', 'spring boot starter jersey': 'spring boot',
  'spring boot starter quartz': 'spring boot', 'spring boot starter integration': 'spring boot',
  'spring boot starter session': 'spring boot', 'spring boot starter mobile': 'spring boot',
  'spring boot starter facebook': 'spring boot', 'spring boot starter linkedin': 'spring boot',
  'spring boot starter twitter': 'spring boot', 'spring boot starter social': 'spring boot',
  'spring boot starter hateoas': 'spring boot',
};

export function normalizeSkill(skill: string): string {
  const lower = skill.trim().toLowerCase();
  return ALIAS_MAP[lower] ?? lower;
}

export function skillsMatch(candidateSkill: string, requiredSkill: string): boolean {
  return normalizeSkill(candidateSkill) === normalizeSkill(requiredSkill);
}

export function getMatchedSkills(candidateSkills: string[], requiredSkills: string[]): string[] {
  return requiredSkills.filter((r) =>
    candidateSkills.some((c) => skillsMatch(c, r))
  );
}

export function getMissingSkills(candidateSkills: string[], requiredSkills: string[]): string[] {
  return requiredSkills.filter(
    (r) => !candidateSkills.some((c) => skillsMatch(c, r))
  );
}
